name: pps-ci-lab
on:
  push:
jobs:
  Build:
    runs-on: ubuntu-18.04
    steps:
      - uses: joschi/setup-jdk@v2.3.0
        with:
          java-version: 15
      - name: Build
        run:
         ./gradlew check